# Generated by Django 3.1 on 2021-11-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelChains',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state', models.SmallIntegerField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='alias',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
