# Generated by Django 3.1 on 2021-11-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20211113_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotelChains',
            new_name='Chains',
        ),
    ]
