# Generated by Django 3.1 on 2021-11-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20211113_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='chain_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='first_app.chains'),
        ),
    ]
