# Generated by Django 3.1 on 2021-11-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20211113_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chains',
            new_name='Chain',
        ),
    ]
