# Generated by Django 4.0 on 2021-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpartner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelchain',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
